### ISSUE TITLE
Show stack traces

### ISSUE THREAD

**Issue by pavelkostyurin** [mminer/consolation#17]
So maybe this is the question not to the developers of this, but maybe you know the answer.
What should I do (is it possible) to display stack traces for exception messages?

**Comment by pavelkostyurin** [comment]
Adding this to DrawExpandedLog() worked for me.

```
 if (log.type == LogType.Exception && log.stackTrace != "")
                    GUILayout.Label(log.stackTrace);
```

**Comment by mminer** [comment]
I'm going to reopen this — it'd be useful to show the stack trace by clicking on a line. We *store* the stack trace; might as well provide a way to see it.

**Comment by ettmetal** [comment]
I see this is a bit of an old request - are you still considering it? If so, would you consider a PR? No promises that I can, but we've been using the package and it's working real nice for us, stack traces would be an excellent upgrade to our workflow for sure 😊

**Comment by mminer** [comment]
@ettmetal: I definitely still think stack traces are a useful feature to add. A PR would be rad; I’m very happy to take contributions. I’ve been meaning to implement it myself but I just haven’t got around to it.

**Comment by mminer** [comment]
I added the ability to view stack traces in dcd5cd9. Click a log to see the trace appears below it.
![Screen Shot 2023-07-14 at 15 47 42](https://github.com/mminer/consolation/assets/267284/a3b95247-4c53-42f0-be0f-923e580ba132)
