### ISSUE TITLE
high resolution problem

### ISSUE THREAD

**Issue by ALI3D69** [mminer/consolation#18]
Hi
How can i increase the size of buttons and scrolls?
It is very small in high resolution screens.

**Comment by mminer** [comment]
This definitely needs to be addressed. We added font sizing in #16, but we need to add options to resize the UI itself.

**Comment by mminer** [comment]
I added the option to scale the UI in [version 1.1.0](https://github.com/mminer/consolation/releases/tag/1.1.0).

![Consolation Scaling](https://user-images.githubusercontent.com/267284/77030755-e6e69400-695c-11ea-9b96-452480aebb50.gif)
