### ISSUE TITLE
Difficult to open console by shaking

### ISSUE THREAD

**Issue by pavelkostyurin** [mminer/consolation#19]
This feature is very useful, although I wonder, have you tried to use it?

I rarely manage to shake device to open console, or to close it again. Phone registers several shakes, which results in opening console and closing it again in a split second. To solve this issue, I added Thread.sleep

```
// Shake it again to hide console
            if (shakeToOpen && Input.acceleration.sqrMagnitude > shakeAcceleration)
            {
                isVisible = !isVisible;
                Thread.Sleep(500);
            }
```

Now I have half a second to give my phone a good shake, and it registered as one shake. Similar with closing console.

**Comment by mminer** [comment]
This past week I received an in-person report that shake-to-open no longer works. Opening and closing immediately might be the culprit. I'll look into this.

I'm tempted to add something like `lastOpenedViaShake` rather than calling `Thread.Sleep`, but that's a good starting place.

**Comment by pavelkostyurin** [comment]
It was always working for me, just tricky to shake device _right_ way. As a guess, that person could set up too high/low acceleration speed via the editor, hence didn't work.

**Comment by jhocking** [comment]
btw my recent commits included a threshold time for shakes, so it won't immediately close after opening

**Comment by mminer** [comment]
@jhocking Ah that's right, your changes in 55364aa0bc9e4d6a230a818bd24fe46141780b99 should address this. Rock on comrades.
