### ISSUE TITLE
collpasing multip logs

### ISSUE THREAD

**Issue by harrywenjie** [mminer/consolation#22]
The unity editor log system would collapse multip repeating logs. While this in game console only collpase last one. Not a big problem, just something to improve.

**Comment by mminer** [comment]
It used to collapse repeating logs; I must have broke this functionality at some point. Will investigate.

**Comment by mminer** [comment]
In my testing, multiple repeated logs collapse correctly when I check the "Collapse" option. I'm going to close this issue, but feel free to reopen if the behaviour is buggy.
![Screen Shot 2023-07-11 at 16 23 24](https://github.com/mminer/consolation/assets/267284/0396c7ef-add7-42d5-a973-185da1cafb0f)
