### ISSUE TITLE
Make the vertical scrollbar wider without affecting the scale

### ISSUE THREAD

**Issue by jgalmeidah** [mminer/consolation#24]
I have been successfully using the consolation on an android phone, but the vertical scrollbar is too thin to get to properly.  
One solution is to increase the scale.
I think it would be better to have an ability to make the scrollbar wider.

**Comment by mminer** [comment]
I can see how the standard scrollbar could be hard to select on mobile. I'm fairly certain `GUILayout` allows us to customize this; should be straightforward.

**Comment by mminer** [comment]
I added the option to apply a custom `GUISkin` to the window. 
![Screen Shot 2023-07-12 at 09 00 05](https://github.com/mminer/consolation/assets/267284/f9e20c7e-93fb-430a-b6ba-f562085c6b56)

This allows you to customize the scrollbar width (and any other style).
![Screen Shot 2023-07-12 at 08 59 44](https://github.com/mminer/consolation/assets/267284/a40cb9b2-958c-4c35-b8af-66a3ba95f06b)
