### ISSUE TITLE
Consolation for UI (VR)

### ISSUE THREAD

**Issue by SebastianJiroSchlecht** [mminer/consolation#26]
I like to use the consolation to display debug messages in a VR canvas text field, e.g., world space. The default GUI of consolation does not display anywhere in VR with the XR Interaction Toolkit.

Is there a (simple) way to adapt consolation to work with the new UI system?

**Comment by mminer** [comment]
Hmm, interesting use case. I doubt think there’s a trivial way to make it work in VR if `GUILayout` is unsupported, but perhaps migrating to a newer GUI system is a good idea in the long run.

**Comment by SebastianJiroSchlecht** [comment]
Thanks for the feedback. In fact, I looked at a few other in-game console outputs. However, at least with the free ones, none worked out-of-the-box in VR. I also realize that this might be quite a different implementation, so not necessarily compatible with the current use case.
