### ISSUE TITLE
Suggestion: scale font size if shakeToOpen

### ISSUE THREAD

**Issue by jelling** [mminer/consolation#27]
The text size was unreadable on my iPhone so I added a scaling factor, implicitly for iOS as I hope no one is shaking their laptops:

```
        void Start()
        {
            if (openOnStart)
            {
                isVisible = true;
            }

            // new line 
            logFontSize = shakeToOpen ? logFontSize * 3 : logFontSize;
        }
```

A small thing but could be helpful for new users.

**Comment by mminer** [comment]
We definitely need to get a better handle on UI scaling on different devices. I'm hesitant to use `shakeToOpen` to implicitly check for mobile builds, but I'll keep this open until we have a better general solution.

**Comment by mminer** [comment]
In 905666d I made the `Console` class properties public so that they can be modified outside the component. This way you can write something like this to change the scale factor on iOS:

```csharp
void Awake()
{
    var console = GetComponent<Console>();

    if (Application.platform == RuntimePlatform.IPhonePlayer)
    {
        console.logFontSize *= 30;
    }
}
```
