### ISSUE TITLE
Build error when included in player

### ISSUE THREAD

**Issue by duckblaster** [mminer/consolation#32]
`EditorGUIUtility.whiteTexture` is referenced regardless of whether `UNITY_EDITOR` is defined, causing player builds to fail.
Maybe replace with `Texture2D.whiteTexture` ?

**Comment by mminer** [comment]
Thanks for highlighting this. I pushed [v1.4.1](https://github.com/mminer/consolation/releases/tag/1.4.1) with the fix. Serves me right for not building a player in a while.
