### ISSUE TITLE
Why does not remove "HandleLog", When Console.OnDisable is invoked?

### ISSUE THREAD

**Issue by ikpil** [mminer/consolation#5]
void OnEnable()
        {
			Application.logMessageReceived += HandleLog;
        }

        void OnDisable()
        {
			Application.logMessageReceived += HandleLog;
                        // Application.logMessageReceived -= HandleLog; <-- Is not this right?
        }

**Comment by mminer** [comment]
Ah you're right, that's a mistake. I'll get that fixed. Thanks for pointing it out.
