### ISSUE TITLE
Scroll To End

### ISSUE THREAD

**Issue by ChrisLangsenkamp** [mminer/consolation#6]
How can I get it to scroll to the last entry automatically?

Answer: Change line 79-ish to...
scrollPosition = GUILayout.BeginScrollView(new Vector2(0, 999999));

**Comment by mminer** [comment]
Huh. I thought it used to scroll to the bottom automatically, but clearly no code currently does that. I'll implement this fix shortly. However, I think the appropriate behaviour is to scroll to the last entry automatically *unless* the user has scrolled up to look at a previous message, in which case changing their scroll position when a new message arrives would be unwelcome. So the logic might be slightly more complex.

**Comment by JamesAMD** [comment]
@mminer I would also love that feature!!

**Comment by mminer** [comment]
The window now scrolls to the last entry, *unless* you manually scroll up to see old logs. After doing so, to return to the auto-scrolling behaviour, simply scroll to the end again.
